### ISSUE TITLE
수강신청 목록 페이지 삭제

### ISSUE THREAD

**Issue by SDI998** [JavaConsoleProgram/EnrolmentWebProject#6]
현재 수강신청 목록 페이지가 필요없는 거 같습니다.
목록 보기는 시간표와 통합하고
시간표 선택시 시간표로 보기/ 목록으로 보기 선택할 수 있게 하기-> 네이버 카페 글 목록 보는 방식 선택하는 것처럼
취소는 수강신청하기 페이지에서 같이 하는 게 이용자가 더 편리하게 쓸 수 있다 생각합니다.

**Comment by accidentlywoo** [comment]
Notion이나 PPT로 화면구성내용을 공유해주세요!
