### ISSUE TITLE
담당 페이지에 필요한 데이터 도출이 필요합니다! [Model 도출하기]

### ISSUE THREAD

**Issue by accidentlywoo** [JavaConsoleProgram/EnrolmentWebProject#9]
[첨성대 프로젝트 관리 엑셀 - Model 설계](https://docs.google.com/spreadsheets/d/1lL3Us2cSsa0Fj62M1vBcEdWMRWoVde5Oeumvuy7qcvc/edit#gid=1511976076)

담당 페이지에서 필요한 데이터들을 도출해주세요!
Ex) 수강신청 리스트의 
[전공/교양-교과목번호-교과목명-학점-강의시간-수강정원-수강신청인원-교수명- 강의실정보-재수강해당]

VO클래스와 다르게 화면에서 요구되는 데이터를 모델링한 클래스입니다. 변경이 잦은 클래스로, 화면에서 보여줄 데이터를 담당합니다.

**Comment by SDI998** [comment]
[전공/교양-교과목번호-교과목명-학점-강의시간-수강정원-수강신청인원-교수명- 강의실정보-재수강해당]

**Comment by SDI998** [comment]
시간표
교과목명-강의시간-교수명- 강의실정보
